name: Deployment

on:
  pull_request:
    branches:
      - master
      - develop
      - stage
    types: [closed]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  build_and_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy (Develop)
        if: github.base_ref == 'develop'
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: app-testnets.thespace.game
          bucket-region: ap-southeast-1
          dist-id: EVWV6S8G4YU1I
          invalidation: /
          delete-removed: true

      - name: Deploy (Production)
        if: github.base_ref == 'main'
        uses: reggionick/s3-deploy@v3
        with:
          folder: build
          bucket: app.thespace.game
          bucket-region: ap-southeast-1
          dist-id: E29ZFXXINKSOH
          invalidation: /
          delete-removed: true
